FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=development
COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund
COPY tsconfig.json tsconfig.node.json index.html vite.config.ts postcss.config.js tailwind.config.js ./
COPY src ./src
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
